import { ServiceEntity } from "../types";
import { ServiceType } from "../types";
import { SERVICE_DESCRIPTIONS, SERVICE_KEYWORDS } from "../schemas";

/**
 * Seed data: Top 10 E-Waste Services with geo associations and FAQ mappings
 */
export const SEED_SERVICES: ServiceEntity[] = [
  {
    id: "service_battery_recycling",
    type: "service",
    name: "Battery Recycling Service",
    description: SERVICE_DESCRIPTIONS[ServiceType.BATTERY_RECYCLING].description,
    slug: "battery-recycling",
    serviceType: ServiceType.BATTERY_RECYCLING,
    keywords: SERVICE_KEYWORDS[ServiceType.BATTERY_RECYCLING],
    relatedServices: [
      { type: "service", id: "service_material_recovery" },
      { type: "service", id: "service_ewaste_collection" },
    ],
    certifications: [
      { type: "certification", id: "cert_r2" },
      { type: "certification", id: "cert_iso_14001" },
    ],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [
      { type: "faq", id: "faq_battery_1" },
      { type: "faq", id: "faq_battery_2" },
    ],
    benefits: [
      "Recovers valuable materials like lithium and cobalt",
      "Reduces environmental contamination from heavy metals",
      "Complies with RoHS and WEEE regulations",
      "Certified and documented disposal process",
    ],
    processSteps: [
      "Collection and sorting of batteries by chemistry",
      "Pre-processing and categorization",
      "Mechanical or chemical extraction",
      "Purification and refinement of recovered materials",
      "Quality testing and packaging",
    ],
    environmentalImpact:
      "Prevents 98% of battery waste from landfills, recovering lithium, cobalt, and nickel for reuse",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_hard_drive_shredding",
    type: "service",
    name: "Hard Drive Shredding & Data Destruction",
    description: SERVICE_DESCRIPTIONS[ServiceType.HARD_DRIVE_SHREDDING].description,
    slug: "hard-drive-shredding",
    serviceType: ServiceType.HARD_DRIVE_SHREDDING,
    keywords: SERVICE_KEYWORDS[ServiceType.HARD_DRIVE_SHREDDING],
    relatedServices: [
      { type: "service", id: "service_data_destruction" },
      { type: "service", id: "service_component_refurbishment" },
    ],
    certifications: [
      { type: "certification", id: "cert_naid" },
      { type: "certification", id: "cert_nist_800_88" },
    ],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [
      { type: "faq", id: "faq_shredding_1" },
      { type: "faq", id: "faq_shredding_2" },
    ],
    benefits: [
      "NAID and NIST 800-88 certified destruction",
      "Complete data security compliance",
      "Certificate of destruction provided",
      "Environmentally responsible material recovery",
    ],
    processSteps: [
      "Data verification and cataloging",
      "Cryptographic erasure or physical destruction",
      "Mechanical shredding to <1cm particles",
      "Material sorting and recycling",
      "Certificate of destruction generation",
    ],
    environmentalImpact: "Recovers 85% of materials from hard drives, preventing toxic landfill disposal",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_itad",
    type: "service",
    name: "IT Asset Disposition (ITAD)",
    description: SERVICE_DESCRIPTIONS[ServiceType.ITAD].description,
    slug: "itad-services",
    serviceType: ServiceType.ITAD,
    keywords: SERVICE_KEYWORDS[ServiceType.ITAD],
    relatedServices: [
      { type: "service", id: "service_component_refurbishment" },
      { type: "service", id: "service_data_destruction" },
    ],
    certifications: [
      { type: "certification", id: "cert_r2" },
      { type: "certification", id: "cert_naid" },
    ],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [
      { type: "faq", id: "faq_itad_1" },
      { type: "faq", id: "faq_itad_2" },
    ],
    benefits: [
      "Maximizes asset recovery value",
      "Manages full lifecycle from pickup to certification",
      "Ensures data security and compliance",
      "Provides detailed audit trails",
    ],
    processSteps: [
      "Asset inventory and documentation",
      "Data erasure and security verification",
      "Functional testing and grading",
      "Refurbishment for secondary markets",
      "Final reporting and certification",
    ],
    environmentalImpact: "Extends product lifecycles, diverting 95% of IT equipment from landfills",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_ewaste_collection",
    type: "service",
    name: "E-Waste Collection Service",
    description: SERVICE_DESCRIPTIONS[ServiceType.EWASTE_COLLECTION].description,
    slug: "ewaste-collection",
    serviceType: ServiceType.EWASTE_COLLECTION,
    keywords: SERVICE_KEYWORDS[ServiceType.EWASTE_COLLECTION],
    relatedServices: [
      { type: "service", id: "service_logistics" },
      { type: "service", id: "service_material_recovery" },
    ],
    certifications: [{ type: "certification", id: "cert_iso_14001" }],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [{ type: "faq", id: "faq_collection_1" }],
    benefits: [
      "Convenient door-to-door pickup",
      "Compliant with e-waste management rules",
      "Segregated and documented collection",
      "Tracking and reporting available",
    ],
    processSteps: [
      "Schedule collection online or via phone",
      "Pre-inspection and cataloging",
      "Safe pickup and transportation",
      "Delivery to authorized recycling facility",
      "Collection report provided",
    ],
    environmentalImpact: "Prevents illegal dumping and ensures proper e-waste management for 1000+ items annually",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_component_refurbishment",
    type: "service",
    name: "Component Refurbishment & Remarketing",
    description: SERVICE_DESCRIPTIONS[ServiceType.COMPONENT_REFURBISHMENT].description,
    slug: "component-refurbishment",
    serviceType: ServiceType.COMPONENT_REFURBISHMENT,
    keywords: SERVICE_KEYWORDS[ServiceType.COMPONENT_REFURBISHMENT],
    relatedServices: [
      { type: "service", id: "service_itad" },
      { type: "service", id: "service_material_recovery" },
    ],
    certifications: [
      { type: "certification", id: "cert_r2" },
      { type: "certification", id: "cert_iso_14001" },
    ],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [{ type: "faq", id: "faq_refurb_1" }],
    benefits: [
      "Extends product lifespan by 5-7 years",
      "Affordable electronics for emerging markets",
      "Quality tested and warranted components",
      "Reduces e-waste significantly",
    ],
    processSteps: [
      "Component testing and diagnostics",
      "Cleaning and inspection",
      "Repair or replacement of faulty parts",
      "Software installation and verification",
      "Packaging and distribution",
    ],
    environmentalImpact: "Diverts 40,000+ refurbished components annually from landfills",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_data_destruction",
    type: "service",
    name: "Certified Data Destruction",
    description: SERVICE_DESCRIPTIONS[ServiceType.DATA_DESTRUCTION].description,
    slug: "data-destruction",
    serviceType: ServiceType.DATA_DESTRUCTION,
    keywords: SERVICE_KEYWORDS[ServiceType.DATA_DESTRUCTION],
    relatedServices: [
      { type: "service", id: "service_hard_drive_shredding" },
      { type: "service", id: "service_assessment" },
    ],
    certifications: [
      { type: "certification", id: "cert_nist_800_88" },
      { type: "certification", id: "cert_naid" },
    ],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [
      { type: "faq", id: "faq_data_1" },
      { type: "faq", id: "faq_data_2" },
    ],
    benefits: [
      "NIST 800-88 and GDPR compliant",
      "Cryptographic erasure available",
      "Certificate of destruction provided",
      "No data recovery possible",
    ],
    processSteps: [
      "Data inventory and risk assessment",
      "Secure transport with tracking",
      "Cryptographic erasure or physical destruction",
      "Verification of complete erasure",
      "Certificate and audit report generation",
    ],
    environmentalImpact: "Protects 100,000+ data points daily while ensuring responsible device recycling",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_material_recovery",
    type: "service",
    name: "Precious Metal & Material Recovery",
    description: SERVICE_DESCRIPTIONS[ServiceType.MATERIAL_RECOVERY].description,
    slug: "material-recovery",
    serviceType: ServiceType.MATERIAL_RECOVERY,
    keywords: SERVICE_KEYWORDS[ServiceType.MATERIAL_RECOVERY],
    relatedServices: [
      { type: "service", id: "service_battery_recycling" },
      { type: "service", id: "service_ewaste_collection" },
    ],
    certifications: [
      { type: "certification", id: "cert_r2" },
      { type: "certification", id: "cert_iso_14001" },
    ],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [{ type: "faq", id: "faq_materials_1" }],
    benefits: [
      "Recovers 95% of materials",
      "Economic value recovery",
      "Reduces mining environmental impact",
      "Circular economy contribution",
    ],
    processSteps: [
      "Comminution and grinding",
      "Physical and chemical separation",
      "Precious metal extraction",
      "Purification and refining",
      "Sale to secondary material markets",
    ],
    environmentalImpact: "Avoids 1500 tons of mining waste per ton of material recovered",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_certification",
    type: "service",
    name: "E-Waste Compliance & Certification",
    description: SERVICE_DESCRIPTIONS[ServiceType.CERTIFICATION].description,
    slug: "certification-services",
    serviceType: ServiceType.CERTIFICATION,
    keywords: SERVICE_KEYWORDS[ServiceType.CERTIFICATION],
    relatedServices: [
      { type: "service", id: "service_assessment" },
    ],
    certifications: [],
    serviceCenters: [],
    faqs: [{ type: "faq", id: "faq_cert_1" }],
    benefits: [
      "NAID, R2, ISO certifications",
      "Legal compliance assurance",
      "Industry credibility enhancement",
      "Market access improvement",
    ],
    processSteps: [
      "Audit of current processes",
      "Gap analysis and recommendations",
      "Implementation support",
      "Final certification audit",
      "Annual compliance reviews",
    ],
    environmentalImpact: "Ensures 100% compliant e-waste management across certified partners",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_assessment",
    type: "service",
    name: "E-Waste Management Assessment",
    description: SERVICE_DESCRIPTIONS[ServiceType.ASSESSMENT].description,
    slug: "assessment-services",
    serviceType: ServiceType.ASSESSMENT,
    keywords: SERVICE_KEYWORDS[ServiceType.ASSESSMENT],
    relatedServices: [
      { type: "service", id: "service_certification" },
    ],
    certifications: [
      { type: "certification", id: "cert_iso_14001" },
      { type: "certification", id: "cert_iso_45001" },
    ],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
    ],
    faqs: [{ type: "faq", id: "faq_assess_1" }],
    benefits: [
      "Comprehensive audit reports",
      "Risk identification and mitigation",
      "Compliance roadmap provided",
      "Industry best practices shared",
    ],
    processSteps: [
      "On-site inspection",
      "Process documentation review",
      "Interviews with key staff",
      "Report generation with recommendations",
      "Follow-up consultation",
    ],
    environmentalImpact: "Identifies improvement opportunities preventing 100+ tons of improper waste disposal",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service_logistics",
    type: "service",
    name: "E-Waste Logistics & Transportation",
    description: SERVICE_DESCRIPTIONS[ServiceType.LOGISTICS].description,
    slug: "logistics-services",
    serviceType: ServiceType.LOGISTICS,
    keywords: SERVICE_KEYWORDS[ServiceType.LOGISTICS],
    relatedServices: [
      { type: "service", id: "service_ewaste_collection" },
    ],
    certifications: [{ type: "certification", id: "cert_iso_45001" }],
    serviceCenters: [
      { type: "location", id: "service_center_kochi_main" },
      { type: "location", id: "service_center_mumbai_processing" },
    ],
    faqs: [{ type: "faq", id: "faq_logistics_1" }],
    benefits: [
      "Safe and compliant transportation",
      "Real-time tracking available",
      "Insurance coverage included",
      "Multi-modal transport options",
    ],
    processSteps: [
      "Pickup scheduling and confirmation",
      "Secure packaging and labeling",
      "GPS-tracked transport",
      "Chain of custody documentation",
      "Delivery confirmation",
    ],
    environmentalImpact: "Ensures 100% compliant hazardous waste transport preventing environmental spillage",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];
